require_relative 'lib/server'
require_relative 'lib/ufw'
require_relative 'lib/vsftpd'

servers = [
  UfwServer.new("ufw", "192.168.50.3"),
  VsftpdServer.new("vsftpd", "192.168.50.2")
]

def setup_and_provision(config, server)
  config.vm.define server.name.downcase.gsub(/\s+/, "") do |srv|
    srv.vm.box = "ubuntu/noble64"
    srv.vm.network "private_network", ip: server.ip_address
    srv.vm.hostname = server.name
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
    srv.vm.provision "shell", inline: server.provision_commands
  end
end

Vagrant.configure("2") do |config|
  servers.each do |server|
    setup_and_provision(config, server)
  end
end
